### ISSUE TITLE
Build weather reporting tool

### ISSUE THREAD

**Issue by davidwollmann** [converter/weather-report#1]
### TODO
- [x] Allow user to search for current weather conditions, using https://openweathermap.org/api API, by:
  - [x] city
  - [x] zip code
  - [x] GPS, reverse geolocation
- [x] documentation with example inputs

> Take Home Assignment: Sr. Agile Engineer – Mobile
> 
> Build an application using whatever tools, components, or third party libraries that you'd like. The app should allow a user to search for current weather conditions by city name, zip code, or coordinates (GPS, reverse geolocation) using the the https://openweathermap.org/api API. The application should be organized in a way where new features can be easily added and/or tested and that you would be happy to maintain. Be sure to submit documentation on how to run the application, including some example inputs.
> 
> You can generate your own API for free but it can take several days to become active.
> 
> Here is an API Token you can use in the meantime: cf002751564a4c78f5f7ed479f1b9ba3

**Comment by davidwollmann** [comment]
closing, MVP is done
